config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "user/registrations" }
  resources :user_stocks, except: [:show, :edit, :update]
  resources :users, only: [:show]
  resources :friendships
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#index'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stocks', to: 'stocks#search'
  resources :user_stocks, only: [:create, :destroy]
  get 'my_friends', to: 'users#my_friends'
  get 'search_friends', to: 'users#search'

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, :class_name => 'User'
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks
 
 
  def self.find_by_ticker(ticker_symbol)
    where(ticker: ticker_symbol).first
  end
 
 
  def self.new_from_lookup(ticker_symbol)
    begin
      client = IEX::Api::Client.new(publishable_token: 'pk_4a121dbab78a4737880847302dddf9b8')
      looked_up_stock = client.quote(ticker_symbol)
      new(name: looked_up_stock.company_name,
          ticker: looked_up_stock.symbol, last_price: looked_up_stock.latest_price)
    rescue Exception => e
      return nil
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships

  def full_name
    return "#{first_name} #{last_name}".strip if (first_name || last_name)
    "Anonymous"
  end

  def stock_already_added?(ticker_symbol)
    stock = Stock.find_by_ticker(ticker_symbol)
    return false unless stock 
    user_stocks.where(stock_id: stock.id).exists?
  end

  def under_stock_limit?
    (user_stocks.count < 10)
  end

  def can_add_stock?(ticker_symbol)
    under_stock_limit? && !stock_already_added?(ticker_symbol)
  end

  def self.search(param)
    para.strip!
    param.downcase!
    to_send_back = (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
    return nil unless to_send_back
    to_send_back
  end

  def self.first_name_matches(param)
    matches('first_name', param)
  end

  def self.last_name_matches(param)
    matches('last_name', param)
  end

  def self.email_matches(param)
    matches('email', param)
  end

  def self.matches(field_name, param)
    User.where("#{field_name} like ?", "%#{param}%")
  end

end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

  def search
    if params[:stock].blank?
      flash.now[:warning] = "You have entered an empty search string"
    else
      @stock = Stock.new_from_lookup(params[:stock])
      flash.now[:warning] = "You have entered an incorrect symbol"
    unless @stock
    end
      respond_to do |format|
        format.js { render partial: 'users/result' }
      end 
    end
  end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
  def create
    stock = Stock.find_by_ticker(params[:stock_ticker])
    if stock.blank?
      stock = Stock.new_from_lookup(params[:stock_ticker])
      stock.save
    end
    @user_stock = UserStock.create(user: current_user, stock: stock)
    flash[:success] = "Stock #{@user_stock.stock.name} was successfully added to portfolio"
    redirect_to my_portfolio_path
  end
  
  def destroy
    stock = Stock.find(params[:id])
    @user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id).first
    @user_stock.destroy
    flash[:success] = "Stock was successfully removed from portfolio"
    redirect_to my_portfolio_path

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def my_portfolio
    @user = current_user
    @user_stocks = current_user.stocks

  end
  
  def my_friends
    @friendships = current_user.friends
  end

  def search
        if params[:search_param].blank?
          flash.now[:warning] = "You have entered an empty search string"
        else
          @users = User.search(params[:search_param])
          flash.now[:warning] = "No users match this search criteria" if @users.blank?
        unless @stock
        end
            render partial: 'friends/result' 
          end 
        end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/views/friends/_lookup.html.erb
<h1 class="ui center aligned icon header">
  <i class="circular  yellow users  icon"></i>
</h1>
<br>
<div class="ui container">
<h3>Search for friends</h3>
  <div class="friend-lookup">
    <%= form_tag search_friends_path, remote: true, method: :get, id: "friend-lookup-form" do %>
      <div class="ui form">
        <div class="ten wide column">
          <%= text_field_tag :search_param, params[:search_param], 
                                placeholder: "Enter name or email", autofocus: true,
                                class: "seven wide field" %>
        </div><br>
          <div class="four wide column">
            <%= button_tag(type: :submit, class: "ui black button", id: "search-button") do %>
            <i class="search icon"></i> Look up a friend
          <% end %>
          </div>
        </div>
      </div>
    <% end %>
</div>

app/views/layouts/_footer.html.erb
<div class="ui container">
<footer class="footer">
  <small>
    Copyright &copy; by Frank Ruiz
  </small>
</footer>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |message_type, message_content| %>
  <div class="ui <%= message_type %> message transition">
    <i class="close icon"></i>
    <div class="header">
      <%= message_content %>
    </div>
  </div>

<% end %>

app/views/layouts/_navigation.html.erb
<div class="ui top inverted menu" id="navbar">
<%= link_to "Stock Tracker", root_path, class: "item", id: "logo" %>
  <% if current_user %>
    <%= link_to "My Portfolio", my_portfolio_path, class: "item" %>
    <%= link_to "My Friends", my_friends_path, class: "item" %>
    <div class="right menu">
     <li class="item">
      <i class="user icon"></i>
        <%= current_user.full_name.present? ? current_user.full_name : current_user.email %>
    </li>
      <% unless user_signed_in?  %>
      <%= link_to  new_user_registration_path ,class: "item" do%>
        <i class="signup icon"></i> Sign Up
      <% end %>
      <%= link_to  new_user_session_path, class: "item" do %>
        <i class="sign in icon"></i> Login
      <% end %>
      <% else %>
      <%= link_to  edit_user_registration_path , class: "item" do %>
        <i class="settings icon"></i> Settings
      <% end %>
      <%= link_to  destroy_user_session_path ,method: :delete, data: {confirm: "Are you sure?"}, class: "item" do %>
        <i class="sign out icon"></i> Logout
      <% end %>
    <% end %>
  </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://fonts.googleapis.com/css?family=Cuprum&display=swap" rel="stylesheet">
    <title>FinanceTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    

    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/stocks/_list.html.erb
<div class="ui container">
  <table class="ui celled striped table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Symbol</th>
        <th>Price</th>
        <% if @user.id == current_user.id  %>
        <th>Actions</th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @user_stocks.each do |user_stock| %>
        <tr>
          <td><%= user_stock.name %></td>
          <td><%= user_stock.ticker %></td>
          <td><%= user_stock.last_price %></td>
          <% if @user.id == current_user.id %>
          <td><%= link_to "Delete this stock", user_stock_path(user_stock), method: :delete,
                          data: {confirm: "Are you sure?"}, class: "ui red button" %>
          </td>
          <% end %>
        </tr>
        <% end %>
    </tbody>
  </table>
</div>

app/views/users/_result.html.erb
<% if @stock %>
  <div class="ui fluid image">
    <div class="ui tag label" id="results-tag">
      <strong>Symbol: </strong> <%= @stock.ticker %> 
      <strong>Name: </strong> <%= @stock.name %> 
      <strong>Price: </strong> <%= @stock.last_price %>
        <div class="top right attached label">
          <% if current_user.can_add_stock?(@stock.ticker) %>
            <%= link_to "Add to my stocks", user_stocks_path(user: current_user, stock_ticker: @stock.ticker), class: "ui black right ribbon label", method: :post %>  
          <% else %>
            Stock cannot be added because you have already added
          <% if !current_user.under_stock_limit? %>
            10 stocks
          <% end %>
          <% if current_user.stock_already_added?(@stock.ticker) %>
            this stock
          <% end %>
    </div>
  </div>
<% end %>
<% end %>

  
 

app/views/users/_result.js.erb
$('#results').html("<%= j (render 'users/result.html') %>")

app/views/users/my_friends.html.erb
<%= render 'friends/lookup' %>
<% if @friendships.size > 0 %>
    <div class="ui container">
  <table class="ui celled striped table">
    <thead>
      <tr>
        <th>
          <h2>My Friends</h2>
        </th>
        <th>Name</th>
        <th>Email</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @friendships.each do |friend| %>
        <tr>
          <td><%= friend.full_name %></td>
          <td><%= friend.email %></td>
          <td>
          <%= link_to "View Profile", user_path(friend), class: "ui black button" %>
          <%= link_to "Remove Friend", friendship_path(friend), method: :delete,
                          data: {confirm: "Are you sure?"}, class: "ui red button" %>
          </td>
        </tr>
        <% end %>
    </tbody>
  </table>
</div>

<% else %>

<div class="row">
  <h2>You dont have any friends yet. Please add some!</h2>
</div>
<% end %>

app/views/users/my_portfolio.html.erb
<h1 class="ui center aligned icon header">
  <i class="circular  yellow folder icon"></i>
  My Portfolio
</h1>
<br>
<div class="ui container">
<h3>Search for Stocks</h3>
  <div class="stock-lookup">
    <%= form_tag search_stocks_path, remote: true, method: :get, id: "stock-lookup-form" do %>
      <div class="ui form">
        <div class="ten wide column">
          <%= text_field_tag :stock, params[:stock], 
                                placeholder: "Stock ticker symbol", autofocus: true,
                                class: "seven wide field" %>
        </div><br>
          <div class="four wide column">
            <%= button_tag(type: :submit, class: "ui black button", id: "search-button") do %>
            <i class="search icon"></i> Look up a stock
          <% end %>
          </div>
        </div>
      </div>
    <% end %>
</div>
<div id="results">
  <%= render 'users/result' %>
</div>

<%= render 'stocks/list' %>




  

app/views/welcome/index.html.erb
<h1>Welcome to Stock Tracker</h1>


 
    <div class="ui centered billboard ad" id= "hero"></div>
 